const GET_BUGS_REQUEST = "GET_BUGS_REQUEST";
const GET_BUGS_SUCCESS = "GET_BUGS_SUCCESS";
const GET_BUGS_FAILURE = "GET_BUGS_FAILURE";
const ADD_BUG_SUCCESS = "ADD_BUG_SUCCESS";
const ADD_BUG_FAILURE = "ADD_BUG_FAILURE";
